use DEMO_DATABASE;
CREATE OR REPLACE TABLE SD_SALES_DATA
(order_id VARCHAR(20),
order_date DATE,
ship_date DATE,
ship_mode VARCHAR(20),
customer_name VARCHAR(60),
segment VARCHAR(15),
state VARCHAR(100),
country VARCHAR(100),
market VARCHAR(10),
region VARCHAR(20),
product_id STRING,
category VARCHAR(20),
sub_category VARCHAR(20),
product_name STRING,
sales NUMBER(10,0),
quantity NUMBER(10,0),
discount FLOAT,
profit FLOAT,
shipping_cost FLOAT,
order_priority VARCHAR(20),
year INT);

DESCRIBE TABLE SD_SALES_DATA;
SELECT * FROM SD_SALES_DATA;
--COPY OF DATA TABLE  CREATED-
CREATE OR REPLACE TABLE  SD_SALES_DATA_COPY AS
SELECT * FROM SD_SALES_DATA;

DESCRIBE TABLE  SD_SALES_DATA_COPY;
SELECT * FROM SD_SALES_DATA_COPY;
--DROPPED PRIMARY KEY
ALTER TABLE SD_SALES_DATA_COPY
DROP PRIMARY KEY;
---ADDED PRIMARY KEY TO ORDER_ID
alter table SD_SALES_DATA_COPY
ADD PRIMARY KEY(ORDER_ID);
--- TO CHECK DATA TYPES IN TABLE 
select get_ddl('table','SD_SALES_DATA_COPY'); -- order_date and ship_date is in date data type 

---EXTACT THE LAST NUMBER AFTER THE - AND CREATE OTHER COLUMN AND UPDATE IT.
--INSERT INTO SD_SALES_DATA_COPY(ORDER_EXTRACT)
ALTER TABLE SD_SALES_DATA_COPY ADD COLUMN ORDER_EXTRACT VARCHAR(15);

INSERT INTO SD_SALES_DATA_COPY(ORDER_EXTRACT)
SELECT SPLIT_PART(order_id,'-',3)

FROM SD_SALES_DATA_COPY;

SELECT * FROM SD_SALES_DATA_COPY;
---FIND DISCOUNT IS GREATER THAN 0 YES ELSE NO
SELECT *,
CASE 
    WHEN DISCOUNT > '0' THEN 'YES'
    ELSE 'NO'
END AS DISCOUNT_FLAG

FROM SD_SALES_DATA_COPY;

---FIND OUT THE FINAL PROFIT AND PUT IT IN COLUMN FOR EVERY ORDER ID.

SELECT *,
 CASE 
     WHEN PROFIT > '0' THEN PROFIT - SHIPPING_COST
     ELSE -PROFIT-SHIPPING_COST
END AS FINAL_PROFIT
FROM SD_SALES_DATA_COPY;


---FIND OUT HOW MUCH DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT FOR EVERY ORDER ID.
ALTER TABLE SD_SALES_DATA_COPY ADD COLUMN PROCESS_DAYS INT;

INSERT INTO SD_SALES_DATA_COPY(SHIPMENT_DAYS)
SELECT DATEDIFF('DAY',ORDER_DATE,SHIP_DATE)
FROM SD_SALES_DATA_COPY;

SELECT * FROM SD_SALES_DATA_COPY;
-----FLAG THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3  DAYS MAKE 5,LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,LESS THAN 10 BUT MORE THAN 6 MAKE 3,MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID.

SELECT *,
CASE 
     WHEN SHIPMENT_DAYS<= '3' THEN '5'
     WHEN SHIPMENT_DAYS<= '6' AND SHIPMENT_DAYS> '3' THEN '4'
     WHEN SHIPMENT_DAYS< '10' AND SHIPMENT_DAYS> '6' THEN '3'
     ELSE '2'

END AS SHIPMENT_RATING
FROM SD_SALES_DATA_COPY;

SELECT * FROM SD_SALES_DATA_COPY;